import type { Metadata } from "next";
import localFont from "next/font/local";
import { Agdasima } from "next/font/google"; 
import "./globals.css";
import { AuthProvider } from "./context/userContext";

const agdasima = Agdasima({
  weight: ["400", "700"],
  subsets: ["latin"],     
  variable: "--font-agdasima", 
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  console.log("children in layout", children)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${agdasima.variable} antialiased bg-rose-950`}
      >
        <AuthProvider>
          <div className=" text-xl"
           style={{ fontFamily: 'var(--font-agdasima)' }}
          >
          {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
